language: node_js
node_js:
  - "0.6"
  - "0.8"
  - "0.10"
  - "0.12"
  - "4.0"
  - "4.1"
  - "4.2"
  - "4.3"
  - "4.4"
  - "5.0"
  - "5.1"
  - "5.2"
  - "5.3"
  - "5.4"
  - "5.5"
  - "5.6"
  - "5.7"
  - "5.8"
  - "5.9"
  - "5.10"
  - "5.11"
  - "6.0"
  - "6.1"
  - "7"
  - "node"
sudo: false
cache:
  directories:
    - node_modules
before_install:
  # Update Node.js modules
  - "test ! -d node_modules || npm prune"
  - "test ! -d node_modules || npm rebuild"
